import {emitInterface} from "./emitTypes";
import {friendlyHookNames} from "./hookNames";
import type {DiscoveredCollection} from "./types";

const GENERATED_HEADER = `// GENERATED by @terreno/syncdb (terreno-syncdb-codegen). Do not edit.
// Friendly names (useTodos / useTodo / useCreateTodo / …) so this file can
// coexist with RTK openApiSdk.ts. Mutation triggers are synchronous
// ({mutationId, id}) — there is no .unwrap() or per-call isLoading.

import {createCollectionHooks} from "@terreno/syncdb/react";
`;

const retriesLiteral = (retries?: boolean | number): string => {
  if (retries === undefined) {
    return "";
  }
  if (retries === false) {
    return ", retries: false";
  }
  if (retries === true) {
    return ", retries: true";
  }
  return `, retries: ${retries}`;
};

export const emitSdk = ({collections}: {collections: DiscoveredCollection[]}): string => {
  const typeBlocks: string[] = [];
  const hookBlocks: string[] = [];
  const names: string[] = [];

  for (const collection of collections) {
    names.push(collection.collection);
    typeBlocks.push(emitInterface({name: collection.entityName, schema: collection.entitySchema}));
    typeBlocks.push(emitInterface({name: collection.createName, schema: collection.createSchema}));
    typeBlocks.push(emitInterface({name: collection.updateName, schema: collection.updateSchema}));

    const hooks = friendlyHookNames({
      collection: collection.collection,
      entityName: collection.entityName,
    });
    const retries = retriesLiteral(collection.retries);
    hookBlocks.push(`export const {
  useListQuery: ${hooks.list},
  useReadQuery: ${hooks.read},
  useCreateMutation: ${hooks.create},
  useUpdateMutation: ${hooks.update},
  useDeleteMutation: ${hooks.remove},
} = createCollectionHooks<${collection.entityName}, ${collection.createName}, ${collection.updateName}>({collection: "${collection.collection}"${retries}});`);
  }

  const collectionsLiteral = names.map((name) => `"${name}"`).join(", ");
  return [
    GENERATED_HEADER,
    typeBlocks.join("\n\n"),
    "",
    "/** Collections with sync enabled on the backend; pass to createSyncDb. */",
    `export const SYNC_COLLECTIONS = [${collectionsLiteral}] as const;`,
    "",
    hookBlocks.join("\n\n"),
    "",
  ].join("\n");
};

export const applyRetriesOverrides = ({
  collections,
  overrides,
}: {
  collections: DiscoveredCollection[];
  overrides?: Record<string, {retries?: boolean | number}>;
}): DiscoveredCollection[] => {
  if (!overrides) {
    return collections;
  }
  return collections.map((collection) => {
    const retries = overrides[collection.collection]?.retries;
    if (retries === undefined) {
      return collection;
    }
    return {...collection, retries};
  });
};
