[test]
preload = ["../ui/src/bunSetup.ts"]
root = "./src"
coveragePathIgnorePatterns = [
  "**/*.test.ts",
  "dist/**",
  "src/dist/**",
  "**/node_modules/**",
  "../api/**",
]
coverageThreshold = { line = 95, function = 95 }
