// GENERATED by @terreno/syncdb (terreno-syncdb-codegen). Do not edit.
// Friendly names (useTodos / useTodo / useCreateTodo / …) so this file can
// coexist with RTK openApiSdk.ts. Mutation triggers are synchronous
// ({mutationId, id}) — there is no .unwrap() or per-call isLoading.

import {createCollectionHooks} from "@terreno/syncdb/react";

export interface Todo {
  _id: string;
  completed?: boolean;
  ownerId: string;
  priority?: "low" | "medium" | "high";
  tags?: string[];
  title: string;
  updated: string;
  created: string;
  deleted?: boolean;
  _syncPrevStream?: string;
  _syncSeq?: number;
}

export interface CreateTodoBody {
  _id?: string;
  completed?: boolean;
  ownerId?: string;
  priority?: "low" | "medium" | "high";
  tags?: string[];
  title?: string;
  updated?: string;
  created?: string;
  deleted?: boolean;
  _syncPrevStream?: string;
  _syncSeq?: number;
}

export interface UpdateTodoBody {
  _id?: string;
  completed?: boolean;
  ownerId?: string;
  priority?: "low" | "medium" | "high";
  tags?: string[];
  title?: string;
  updated?: string;
  created?: string;
  deleted?: boolean;
  _syncPrevStream?: string;
  _syncSeq?: number;
}

/** Collections with sync enabled on the backend; pass to createSyncDb. */
export const SYNC_COLLECTIONS = ["todos"] as const;

export const {
  useListQuery: useTodos,
  useReadQuery: useTodo,
  useCreateMutation: useCreateTodo,
  useUpdateMutation: useUpdateTodo,
  useDeleteMutation: useDeleteTodo,
} = createCollectionHooks<Todo, CreateTodoBody, UpdateTodoBody>({
  collection: "todos",
  retries: false,
});
