// GENERATED by @terreno/syncdb (terreno-syncdb-codegen). Do not edit.
// Friendly names (useTodos / useTodo / useCreateTodo / …) so this file can
// coexist with RTK openApiSdk.ts. Mutation triggers are synchronous
// ({mutationId, id}) — there is no .unwrap() or per-call isLoading.

import {createCollectionHooks} from "@terreno/syncdb/react";

export interface Todo {
  _id: string;
  title: string;
  completed: boolean;
  ownerId: string;
  created: string;
  updated: string;
}

export interface CreateTodoBody {
  title: string;
  completed?: boolean;
}

export interface UpdateTodoBody {
  title?: string;
  completed?: boolean;
}

/** Collections with sync enabled on the backend; pass to createSyncDb. */
export const SYNC_COLLECTIONS = ["todos"] as const;

export const {
  useListQuery: useTodos,
  useReadQuery: useTodo,
  useCreateMutation: useCreateTodo,
  useUpdateMutation: useUpdateTodo,
  useDeleteMutation: useDeleteTodo,
} = createCollectionHooks<Todo, CreateTodoBody, UpdateTodoBody>({collection: "todos"});
