// GENERATED by @terreno/syncdb-codegen. Do not edit.
// RTK ↔ syncdb hook mapping is documented in docs/how-to/migrate-rtk-to-syncdb.md.

import {createCollectionHooks} from "@terreno/syncdb/react";

export interface Todo {
  _id: string;
  title: string;
  completed?: boolean;
  ownerId?: string;
  created: string;
  updated: string;
}
export interface CreateTodoBody {
  _id?: string;
  title: string;
  completed?: boolean;
  created?: string;
}
export type UpdateTodoBody = Partial<CreateTodoBody>;

export const SYNC_COLLECTIONS = ["todos"] as const;

export const {
  useListQuery: useTodos,
  useReadQuery: useTodo,
  useCreateMutation: useCreateTodo,
  useUpdateMutation: useUpdateTodo,
  useDeleteMutation: useDeleteTodo,
} = createCollectionHooks<Todo, CreateTodoBody, UpdateTodoBody>({collection: "todos", retries: false});
