import {deriveFriendlyHookNames} from "./deriveHookNames";
import {deriveCreateBodyName, deriveUpdateBodyName} from "./discoverCollections";
import {emitInterface, emitPartialType} from "./emitTypes";
import type {CodegenConfigFile, DiscoveredCollection, OpenApiDocument} from "./types";

const GENERATED_HEADER =
  "// GENERATED by @terreno/syncdb-codegen. Do not edit.\n" +
  "// RTK ↔ syncdb hook mapping is documented in docs/how-to/migrate-rtk-to-syncdb.md.\n";

const formatRetries = (retries: boolean | number | undefined): string => {
  if (retries === undefined) {
    return "";
  }
  if (typeof retries === "boolean") {
    return `, retries: ${retries}`;
  }
  return `, retries: ${retries}`;
};

const emitCollectionBlock = (collection: DiscoveredCollection): string => {
  const createBodyName = deriveCreateBodyName(collection.entitySchemaName);
  const updateBodyName = deriveUpdateBodyName(collection.entitySchemaName);
  const hooks = deriveFriendlyHookNames(collection.entitySchemaName, collection.collection);
  const retries = formatRetries(collection.retries);

  return `export const {
  useListQuery: ${hooks.list},
  useReadQuery: ${hooks.read},
  useCreateMutation: ${hooks.create},
  useUpdateMutation: ${hooks.update},
  useDeleteMutation: ${hooks.delete},
} = createCollectionHooks<${collection.entitySchemaName}, ${createBodyName}, ${updateBodyName}>({collection: "${collection.collection}"${retries}});`;
};

export const emitSdk = ({
  doc,
  collections,
  config,
}: {
  doc: OpenApiDocument;
  collections: DiscoveredCollection[];
  config?: CodegenConfigFile;
}): string => {
  const sdkImportPath = config?.sdkImportPath ?? "@terreno/syncdb/react";
  const typeLines: string[] = [];
  for (const collection of collections) {
    const createBodyName = deriveCreateBodyName(collection.entitySchemaName);
    const updateBodyName = deriveUpdateBodyName(collection.entitySchemaName);

    typeLines.push(emitInterface(collection.entitySchemaName, collection.entitySchema, doc));

    if (collection.createSchema) {
      typeLines.push(emitInterface(createBodyName, collection.createSchema, doc));
    } else {
      typeLines.push(`export interface ${createBodyName} extends Record<string, unknown> {}`);
    }

    typeLines.push(emitPartialType(updateBodyName, createBodyName));
  }

  const uniqueTypes = [...new Set(typeLines)];
  const collectionNames = collections.map((entry) => `"${entry.collection}"`).join(", ");
  const blocks = collections.map(emitCollectionBlock).join("\n\n");

  return [
    GENERATED_HEADER,
    `import {createCollectionHooks} from "${sdkImportPath}";`,
    "",
    ...uniqueTypes,
    "",
    `export const SYNC_COLLECTIONS = [${collectionNames}] as const;`,
    "",
    blocks,
    "",
  ].join("\n");
};
