import {deriveFriendlyHookNames} from "./deriveHookNames";
import {deriveCreateBodyName, deriveUpdateBodyName} from "./discoverCollections";
import {emitInterface, emitPartialType} from "./emitTypes";
import {assertTsIdentifier, emitTsString} from "./safeIdentifiers";
import type {CodegenConfigFile, DiscoveredCollection, OpenApiDocument} from "./types";

const GENERATED_HEADER =
  "// GENERATED by @terreno/syncdb-codegen. Do not edit.\n" +
  "// RTK ↔ syncdb hook mapping is documented in docs/how-to/migrate-rtk-to-syncdb.md.\n";

const formatRetries = (retries: boolean | number | undefined): string => {
  if (retries === undefined) {
    return "";
  }
  if (typeof retries === "boolean") {
    return `, retries: ${retries}`;
  }
  if (typeof retries === "number" && Number.isFinite(retries)) {
    return `, retries: ${retries}`;
  }
  throw new Error(`Invalid retries override: ${JSON.stringify(retries)}`);
};

const emitCollectionBlock = (collection: DiscoveredCollection): string => {
  const entitySchemaName = assertTsIdentifier({
    label: "entity schema name",
    value: collection.entitySchemaName,
  });
  const createBodyName = assertTsIdentifier({
    label: "create body name",
    value: deriveCreateBodyName(entitySchemaName),
  });
  const updateBodyName = assertTsIdentifier({
    label: "update body name",
    value: deriveUpdateBodyName(entitySchemaName),
  });
  const collectionName = assertTsIdentifier({
    label: "collection",
    value: collection.collection,
  });
  const hooks = deriveFriendlyHookNames(entitySchemaName, collectionName);
  const list = assertTsIdentifier({label: "hook name", value: hooks.list});
  const read = assertTsIdentifier({label: "hook name", value: hooks.read});
  const create = assertTsIdentifier({label: "hook name", value: hooks.create});
  const update = assertTsIdentifier({label: "hook name", value: hooks.update});
  const deleteHook = assertTsIdentifier({label: "hook name", value: hooks.delete});
  const retries = formatRetries(collection.retries);

  return `export const {
  useListQuery: ${list},
  useReadQuery: ${read},
  useCreateMutation: ${create},
  useUpdateMutation: ${update},
  useDeleteMutation: ${deleteHook},
} = createCollectionHooks<${entitySchemaName}, ${createBodyName}, ${updateBodyName}>({collection: ${emitTsString(collectionName)}${retries}});`;
};

export const emitSdk = ({
  doc,
  collections,
  config,
}: {
  doc: OpenApiDocument;
  collections: DiscoveredCollection[];
  config?: CodegenConfigFile;
}): string => {
  const sdkImportPath = config?.sdkImportPath ?? "@terreno/syncdb/react";
  const typeLines: string[] = [];
  for (const collection of collections) {
    const createBodyName = deriveCreateBodyName(collection.entitySchemaName);
    const updateBodyName = deriveUpdateBodyName(collection.entitySchemaName);

    typeLines.push(emitInterface(collection.entitySchemaName, collection.entitySchema, doc));

    if (collection.createSchema) {
      typeLines.push(emitInterface(createBodyName, collection.createSchema, doc));
    } else {
      typeLines.push(`export interface ${createBodyName} extends Record<string, unknown> {}`);
    }

    typeLines.push(emitPartialType(updateBodyName, createBodyName));
  }

  const uniqueTypes = [...new Set(typeLines)];
  const collectionNames = collections.map((entry) => emitTsString(entry.collection)).join(", ");
  const blocks = collections.map(emitCollectionBlock).join("\n\n");

  return [
    GENERATED_HEADER,
    `import {createCollectionHooks} from ${emitTsString(sdkImportPath)};`,
    "",
    ...uniqueTypes,
    "",
    `export const SYNC_COLLECTIONS = [${collectionNames}] as const;`,
    "",
    blocks,
    "",
  ].join("\n");
};
