/**
 * Prototype generator that turns a backend OpenAPI spec into typed syncdb
 * operation descriptors. It identifies REST resource collections (a `/{name}`
 * list/create path paired with a `/{name}/{id}` item path) and emits a
 * descriptor per collection plus a ready-to-write TypeScript module.
 */

export interface OperationDescriptor {
  method: string;
  path: string;
  operationId?: string;
}

export interface CollectionDescriptor {
  collection: string;
  operations: {
    list?: OperationDescriptor;
    create?: OperationDescriptor;
    read?: OperationDescriptor;
    update?: OperationDescriptor;
    delete?: OperationDescriptor;
  };
}

interface OpenApiOperation {
  operationId?: string;
  tags?: string[];
}

interface OpenApiDocument {
  paths?: Record<string, Record<string, OpenApiOperation>>;
}

const COLLECTION_PATH = /^\/([A-Za-z0-9_-]+)$/;
const ITEM_PATH = /^\/([A-Za-z0-9_-]+)\/\{[A-Za-z0-9_]+\}$/;

const operationOf = (
  pathItem: Record<string, OpenApiOperation>,
  method: string,
  path: string
): OperationDescriptor | undefined => {
  const operation = pathItem[method];
  if (!operation) {
    return undefined;
  }
  return {method, operationId: operation.operationId, path};
};

const buildSource = (descriptors: CollectionDescriptor[]): string => {
  const body = JSON.stringify(
    Object.fromEntries(descriptors.map((descriptor) => [descriptor.collection, descriptor])),
    null,
    2
  );
  return [
    "// Generated by @terreno/syncdb-codegen. Do not edit by hand.",
    `export const syncDbDescriptors = ${body} as const;`,
    "",
    "export type SyncDbDescriptors = typeof syncDbDescriptors;",
    "",
  ].join("\n");
};

/**
 * Generate syncdb descriptors and a source module from an OpenAPI document.
 */
export const generateSyncDbDescriptors = ({
  openapi,
}: {
  openapi: OpenApiDocument;
}): {descriptors: CollectionDescriptor[]; source: string} => {
  const paths = openapi.paths ?? {};
  const byCollection = new Map<string, CollectionDescriptor>();

  const ensure = (collection: string): CollectionDescriptor => {
    const existing = byCollection.get(collection);
    if (existing) {
      return existing;
    }
    const created: CollectionDescriptor = {collection, operations: {}};
    byCollection.set(collection, created);
    return created;
  };

  for (const [path, pathItem] of Object.entries(paths)) {
    const collectionMatch = path.match(COLLECTION_PATH);
    if (collectionMatch) {
      const descriptor = ensure(collectionMatch[1]);
      descriptor.operations.list = operationOf(pathItem, "get", path) ?? descriptor.operations.list;
      descriptor.operations.create =
        operationOf(pathItem, "post", path) ?? descriptor.operations.create;
      continue;
    }

    const itemMatch = path.match(ITEM_PATH);
    if (itemMatch) {
      const descriptor = ensure(itemMatch[1]);
      descriptor.operations.read = operationOf(pathItem, "get", path) ?? descriptor.operations.read;
      descriptor.operations.update =
        operationOf(pathItem, "patch", path) ??
        operationOf(pathItem, "put", path) ??
        descriptor.operations.update;
      descriptor.operations.delete =
        operationOf(pathItem, "delete", path) ?? descriptor.operations.delete;
    }
  }

  // Only keep collections that look like real resources (have at least a
  // list/create and an item-level operation), filtering out one-off endpoints.
  const descriptors = [...byCollection.values()].filter((descriptor) => {
    const ops = descriptor.operations;
    const hasCollectionOp = Boolean(ops.list || ops.create);
    const hasItemOp = Boolean(ops.read || ops.update || ops.delete);
    return hasCollectionOp && hasItemOp;
  });

  return {descriptors, source: buildSource(descriptors)};
};
