// This takes the autogenerated SDK and adds some extra functionality to it. For example,
// we can add extra tags to endpoints.
import startCase from "lodash/startCase";

import {generateTags} from "@terreno/rtk";

import {addTagTypes, openapi} from "./openApiSdk";

// This is where we can modify the SDK. For example,
// we can add a transformResponse to the endpoints or we can add extra tags. We can also add extra
// endpoints, since we don't automatically generate for endpoints that don't use fernsRouter
// currently.

export interface EngagementDataArgs {
	carePodId: string;
	date?: string;
}

export interface PatientEngagementStatsArgs {
	id: string;
}

export interface ExplorerUsersArgs {
	carePodId?: string;
	page?: number;
	limit?: number;
	userStatusId?: string;
	testUsers?: boolean;
	myPanel?: boolean;
}

export interface ExplorerAlertsArgs {
	carePodId?: string;
	page?: number;
	limit?: number;
	userStatusId?: string;
	testUsers?: boolean;
}

export interface OutboundCallArgs {
	callRecipient: {phoneNumber?: string; id?: string; name?: string};
}

export const fernsApi = openapi
	.injectEndpoints({
		endpoints: (_builder) => ({
			// Add any additional endpoints here.
		}),
	})
	// Enhance endpoints is where we can add different tags to endpoints and more complex
	// invalidations.
	.enhanceEndpoints({
		addTagTypes: ["consentForms"],
		endpoints: {
			...generateTags(openapi, addTagTypes),
			// Add any additional endpoints here.
		},
	});

export const {
	useEmailLoginMutation,
	useGoogleLoginMutation,
	useCreateEmailUserMutation,
	useEmailSignUpMutation,
	useResetPasswordMutation,
} = fernsApi;
export * from "./openApiSdk";

// Endpoint type from the OpenAPI generated SDK - uses Record for dynamic structure
type OpenApiEndpoints = Record<string, unknown>;

// Get hooks from the ferns-rtk generated SDK for CRUD/list operations.
// Returns the appropriate RTK Query hook based on model name and operation type
// Return type is Record<string, unknown> as it varies based on operation and model
export const getSdkHook = (
	modelName: string,
	type: "list" | "read" | "create" | "update" | "remove"
): Record<string, unknown> => {
	const modelPath = startCase(modelName).replace(/\s/g, "");
	const endpoints = openapi.endpoints as OpenApiEndpoints;
	switch (type) {
		case "list":
			return endpoints[`get${modelPath}`] as Record<string, unknown>;
		case "read":
			return endpoints[`get${modelPath}ById`] as Record<string, unknown>;
		case "create":
			return endpoints[`post${modelPath}`] as Record<string, unknown>;
		case "update":
			return endpoints[`patch${modelPath}ById`] as Record<string, unknown>;
		case "remove":
			return endpoints[`delete${modelPath}ById`] as Record<string, unknown>;
		default:
			throw new Error(`Invalid SDK hook: ${modelName}/${type}`);
	}
};
