[test]
preload = ["./src/tests/bunSetup.ts"]
root = "./src"
coverage = true
coveragePathIgnorePatterns = ["dist/**", "**/*.test.ts", "**/tests/**", "**/vendor/**", "../**"]
coverageThreshold = { line = 95, function = 95 }

