[test]
preload = ["./src/tests/bunSetup.ts"]
root = "./src"
coverage = true
coveragePathIgnorePatterns = ["dist/**", "**/*.test.ts", "**/tests/**", "**/vendor/**"]
coverageThreshold = { line = 80, function = 80 }

